### ISSUE TITLE
编译hadoop遇到OpensslCipher.c代码报错

### ISSUE THREAD

**Issue by lpf1203** [kunpengcompute/hackathon#8]
![image](https://user-images.githubusercontent.com/73324921/96963481-4a602200-153b-11eb-94e6-d06e8e690226.png)
![image](https://user-images.githubusercontent.com/73324921/96963607-7ed3de00-153b-11eb-8097-22dd48a9faf4.png)

**Comment by huangtianhua** [comment]
see solution: https://github.com/kunpengcompute/hadoop/commit/397fc6a1bfacd5a3b133c3a0356cb3c417b80966

**Comment by liusheng** [comment]
openssl版本不符合要求，需要安装`1.0.x`版本的
```shell
curl -sL https://www.openssl.org/source/old/1.0.1/openssl-1.0.1u.tar.gz | tar zx -C /opt/ \
&& cd /opt/openssl-1.0.1u \
&& ./config --prefix=/usr/local --openssldir=/usr/local/ssl \
&& make \
&& make install
```
